# Generated by Django 3.2.16 on 2022-12-28 09:06

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('keystroke', '0002_post_pure_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pure_data',
            field=jsonfield.fields.JSONField(),
        ),
    ]
