# Generated by Django 3.2.16 on 2023-01-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keystroke', '0003_alter_post_pure_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('n', 'no')], default='n', help_text='Проверка', max_length=1),
        ),
    ]
