# Generated by Django 3.2.16 on 2023-01-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keystroke', '0004_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_to_test',
            field=models.CharField(blank=True, choices=[('y', 'yes'), ('n', 'no')], default='n', help_text='Текст для отображения', max_length=1),
        ),
    ]
