# Generated by Django 3.2.16 on 2022-12-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keystroke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pure_data',
            field=models.TextField(blank=True, default='', max_length=999999, verbose_name='Данные'),
        ),
    ]
